### ISSUE TITLE
Include renderRcode() from gMCPShiny

### ISSUE THREAD

**Issue by wangben718** [Merck/gMCPLite#19]
I am trying to use renderRcode() in another shinyAPP. Is it possible to include renderRcode() in gMCPLite? https://github.com/Merck/gMCPShiny/blob/main/R/output-rcode.R

**Comment by nanxstats** [comment]
No. They are only in gMCPShiny and should be placed there only for a good reason - to maintain a single source of truth. We will work on a CRAN submission for gMCPShiny soon.
